In [61]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

### Q1. Pandas version


In [2]:
pd.__version__

'2.2.2'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-18 04:27:29--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv'

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.04s   

2024-09-18 04:27:29 (7.22 MB/s) - 'laptops.csv' saved [298573/298573]



In [4]:
df = pd.read_csv('laptops.csv')


## Q2. Records count

In [5]:
df.shape

(2160, 12)

In [6]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

## Q3. Laptop brands


In [7]:
len(df['Brand'].unique())

27

## Q4. Missing values


In [8]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

## Q5. Maximum final price

In [9]:
df['Brand'].unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [10]:
df['Model'].unique()

array(['ExpertBook', 'Go', 'Katana', '15S', 'Crosshair', 'ThinkPad',
       'VivoBook', 'Akoya', 'Victus', 'V15', 'Thin', 'ROG', 'IdeaPad',
       'Cyborg', 'M515UA', 'TUF', 'Aspire', 'Pavilion', 'Vector',
       'Chromebook', 'Omen', 'ZenBook', 'Creator', 'MacBook Air',
       'ThinkBook', '250', 'Modern', '255', 'MacBook Pro', 'Prestige',
       'Stealth', 'Pulse', 'Blade', 'Legion', 'Raider', 'ProBook', 'F515',
       'G5', 'Vostro', 'Nitro', 'Gram', 'E410', 'Flex Advance', 'Bravo',
       'Aero', 'Yoga', 'Galaxy Book', 'Erazer', 'Summit', 'Ultra',
       'Extensa', 'Flex', 'EliteBook', 'Revolt', 'Latitude', 'Envy',
       'Deputy', 'Predator', 'Surface Laptop', '14w', 'Titan', 'Ioxbook',
       'Aorus', 'Swift', 'Surface Go', 'Netbook Pro', 'Surface Pro',
       'Notebook', '470', 'Spectre', 'Alurin', 'Satellite Pro', 'XPS',
       'ConceptD', 'E510', 'Beast', 'TravelMate', 'Portégé', 'Tecra',
       'Neo', 'Electronics', '14S', 'Classmate Pro', '17', 'Zbook', 'BR',
       '300w', 

In [11]:
df_dell_brand = df[df['Brand'] == 'Dell']

In [12]:
df_dell_brand['Final Price'].describe()

count      84.000000
mean     1153.839881
std       671.795071
min       379.000000
25%       699.000000
50%      1003.000000
75%      1313.810000
max      3936.000000
Name: Final Price, dtype: float64

## Q6. Median value of Screen


In [14]:
df['Screen'].head()

0    15.6
1    15.6
2    15.6
3    15.6
4    15.6
Name: Screen, dtype: float64

In [17]:
df['Screen'].median()

15.6

In [18]:
df['Screen'].value_counts()

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.50      19
13.40      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
14.40       6
12.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.10       1
10.95       1
Name: count, dtype: int64

In [21]:
df['Screen'] = df['Screen'].fillna(15.60)

In [22]:
df['Screen'].median()

15.6

## Q7. Sum of weights

In [68]:
df_laptop_Innjoo = df[df['Brand']=='Innjoo']
df_laptop_Innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [69]:
df_laptop_Innjoo = df_laptop_Innjoo[['RAM', 'Storage', 'Screen']]

In [70]:
df_laptop_Innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [71]:
X= df_laptop_Innjoo.to_numpy()

In [72]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [73]:
XT = X.T

In [74]:
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [77]:
XTX = np.matmul(XT,X)

In [78]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [80]:
INTX=inv(XTX)

In [81]:
INTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [82]:
y= np.array([1100, 1300, 800, 900, 1000, 1100])

In [86]:
yt = y.T

In [87]:
r1 = np.matmul(INTX, XT)
r1

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [89]:
w=np.matmul(r1, yt)

In [91]:
w.sum()

91.2998806299555